name: presentation

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # state management
  flutter_bloc:

  # di
  get_it:

  # navigation
  auto_route: 4.0.1

  # image
  flutter_svg: 2.0.4

  #sliver
  sliver_tools: 0.2.9

dev_dependencies:
  build_runner:
  auto_route_generator: 4.0.0
  copy_with_extension_gen:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - ../assets/images/